Repository janhq/WhisperSpeech, pull requests merged in 2024-12, with the labels that each got.

#8 fix: training loss stuck bug
  ichigo-quantizer/README.md
  ichigo-quantizer/config/trainer_config.py
  ichigo-quantizer/data/dataset.py
  ichigo-quantizer/data/eda.ipynb
  ichigo-quantizer/data/whisper_dataset.py
  ichigo-quantizer/models/vq_transformer.py
  ichigo-quantizer/scripts/evaluate_bud500.sh
  ichigo-quantizer/scripts/test.py
  ichigo-quantizer/scripts/test.sh
  ichigo-quantizer/scripts/train.py
  ichigo-quantizer/scripts/train.sh
  ichigo-quantizer/trainer/trainer.py
  ichigo-quantizer/trainer/utils.py
Labels: bug

#11 Feat: add normalization
  ichigo-quantizer/trainer/wer_metrics.py
Labels: help wanted

#12 feat: mix multiple language datasets
  ichigo-quantizer/.gitignore
  ichigo-quantizer/config/trainer_config.py
  ichigo-quantizer/data/dataset.py
  ichigo-quantizer/models/factory.py
  ichigo-quantizer/scripts/test.sh
  ichigo-quantizer/scripts/train.py
  ichigo-quantizer/scripts/train.sh
  ichigo-quantizer/scripts/train_multi.sh
  ichigo-quantizer/scripts/train_single.sh
  ichigo-quantizer/trainer/lightning_module.py
  ichigo-quantizer/trainer/trainer.py
  ichigo-quantizer/trainer/utils.py
Labels: enhancement

#13 feat: add tracking, training utils
  ichigo-quantizer/config/trainer_config.py
  ichigo-quantizer/data/dataset.py
  ichigo-quantizer/models/factory.py
  ichigo-quantizer/scripts/test.py
  ichigo-quantizer/scripts/test.sh
  ichigo-quantizer/scripts/train.py
  ichigo-quantizer/scripts/train_multi.sh
  ichigo-quantizer/trainer/lightning_module.py
  ichigo-quantizer/trainer/trainer.py
  ichigo-quantizer/trainer/utils.py
Labels: enhancement

#15 fix: inference use in_toks
  ichigo-quantizer/data/dataset.py
  ichigo-quantizer/models/vq_transformer.py
  ichigo-quantizer/scripts/test.py
  ichigo-quantizer/scripts/test.sh
  ichigo-quantizer/trainer/trainer.py
  ichigo-quantizer/trainer/utils.py
Labels: bug

#14 feat: evaluation
  ichigo-quantizer/.gitignore
  ichigo-quantizer/README.md
  ichigo-quantizer/config/trainer_config.py
  ichigo-quantizer/config/vq_config.py
  ichigo-quantizer/data/dataset.py
  ichigo-quantizer/data/hf.py
  ichigo-quantizer/data/process_data/concat_dataset.py
  ichigo-quantizer/data/process_data/process_gigas.py
  ichigo-quantizer/data/process_data/process_gt.py
  ichigo-quantizer/data/process_data/split_data.py
  ichigo-quantizer/data/process_data/transcribe_dataset.py
  ichigo-quantizer/demo/app.py
  ichigo-quantizer/models/factory.py
  ichigo-quantizer/models/layers.py
  ichigo-quantizer/models/modules.py
  ichigo-quantizer/models/vq_transformer.py
  ichigo-quantizer/requirements.txt
  ichigo-quantizer/scripts/concat_data.sh
  ichigo-quantizer/scripts/test.py
  ichigo-quantizer/scripts/test.sh
  ichigo-quantizer/scripts/train.py
  ichigo-quantizer/scripts/train_multi.sh
  ichigo-quantizer/trainer/lightning_module.py
  ichigo-quantizer/trainer/trainer.py
  ichigo-quantizer/trainer/utils.py
  ichigo-quantizer/trainer/wer_metrics.py
Labels: enhancement

#17 fix: flex language decoding options
  ichigo-quantizer/.gitignore
  ichigo-quantizer/demo/app.py
  ichigo-quantizer/models/vq_transformer.py
Labels: bug

#19 fix: add PAD token
  ichigo-quantizer/data/dataset.py
  ichigo-quantizer/data/hf.py
  ichigo-quantizer/models/vq_transformer.py
  ichigo-quantizer/scripts/test.sh
Labels: bug

#20 feat: merge codebooks
  ichigo-quantizer/data/hf.py
  ichigo-quantizer/demo/app.py
  ichigo-quantizer/models/factory.py
  ichigo-quantizer/models/vq_transformer.py
  ichigo-quantizer/requirements.txt
  ichigo-quantizer/scripts/test.py
  ichigo-quantizer/scripts/test.sh
  ichigo-quantizer/trainer/trainer.py
  ichigo-quantizer/utils/data/libritts 1k - merge 7lang - 512 last - p2 5e.csv
  ichigo-quantizer/utils/data/vivoice 1k - merge 7lang - 512 last - p2 5e.csv
  ichigo-quantizer/utils/data_eda.ipynb
  ichigo-quantizer/utils/token_viz.ipynb
Labels: enhancement

#21 fix: cut pad seq
  ichigo-quantizer/models/vq_transformer.py
Labels: bug

#22 chore: rename to ichigo-whisper
  ichigo-whisper/.gitignore
  ichigo-whisper/README.md
  ichigo-whisper/config/__init__.py
  ichigo-whisper/config/trainer_config.py
  ichigo-whisper/config/vq_config.py
  ichigo-whisper/data/__init__.py
  ichigo-whisper/data/dataset.py
  ichigo-whisper/data/hf.py
  ichigo-whisper/data/process_data/concat_dataset.py
  ichigo-whisper/data/process_data/process_gigas.py
  ichigo-whisper/data/process_data/process_gt.py
  ichigo-whisper/data/process_data/split_data.py
  ichigo-whisper/data/process_data/transcribe_dataset.py
  ichigo-whisper/data/utils.py
  ichigo-whisper/demo/app.py
  ichigo-whisper/models/__init__.py
  ichigo-whisper/models/factory.py
  ichigo-whisper/models/layers.py
  ichigo-whisper/models/modules.py
  ichigo-whisper/models/vq_transformer.py
  ichigo-whisper/requirements.txt
  ichigo-whisper/scripts/concat_data.sh
  ichigo-whisper/scripts/test.py
  ichigo-whisper/scripts/test.sh
  ichigo-whisper/scripts/train.py
  ichigo-whisper/scripts/train_multi.sh
  ichigo-whisper/scripts/train_single.sh
  ichigo-whisper/trainer/__init__.py
  ichigo-whisper/trainer/lightning_module.py
  ichigo-whisper/trainer/trainer.py
  ichigo-whisper/trainer/utils.py
  ichigo-whisper/utils/data/libritts 1k - merge 7lang - 512 last - p2 5e.csv
  ichigo-whisper/utils/data/vivoice 1k - merge 7lang - 512 last - p2 5e.csv
  ichigo-whisper/utils/data_eda.ipynb
  ichigo-whisper/utils/token_viz.ipynb
Labels: documentation

#23 feat: add inference codebase
  ichigo-whisper/demo/app.py
  ichigo-whisper/demo/inference.py
  ichigo-whisper/demo/samples/male_calm.wav
  ichigo-whisper/demo/utils.py
Labels: enhancement

#24 feat: add args inference
  ichigo-whisper/README.md
  ichigo-whisper/demo/inference.py
Labels: enhancement
